name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3.3.0

      - uses: actions/setup-node@v3.6.0
        with:
          node-version-file: ./.node-version
          cache: npm
          cache-dependency-path: ./package-lock.json

      - run: npm ci
      - run: npm run build
      - run: npm run test
      - run: npm run lint
      - run: npm run build-storybook
